### ISSUE TITLE
Directory structure

### ISSUE THREAD

**Issue by glatard** [poldrack/narps#29]
The management of file names and directory structures is a bit tricky to follow. It is not a major issue, but it is distracting to have to think about it constantly through the code. I didn't find any bug in it though. For instance, sections such as:
https://github.com/glatard/narps/blob/5628cef4bcd5694475720456ec48c0741c21e3de/ImageAnalyses/narps.py#L595-L606
could largely be factorized in `NarpsDirs`.

Suggestion: move directory creation (mkdir) and definition (os.path.join) code to NarpsDir as much as possible.

**Comment by poldrack** [comment]
fix in commits leading up to 3a3218e
