### ISSUE TITLE
Overlap images -> mean images

### ISSUE THREAD

**Issue by glatard** [poldrack/narps#31]
Overlap images seem to be mean images across teams. Maybe it would be clearer to rename `create_thresh_overlap_images` to `create_mean_overlap_images` (and update comments accordingly):
https://github.com/poldrack/narps/blob/c6040140573002c4d934046836c2ac1073f51dcc/ImageAnalyses/narps.py#L560

**Comment by poldrack** [comment]
They are mean thresholded images, so I'll use
create_mean_thresholded_images instead

**Comment by poldrack** [comment]
ok, should be fixed in commits leading up to 3a3218e
